# Generated by Django 5.1.3 on 2024-12-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
